IF OBJECT_ID('dbo.CrArMst', 'U') IS NOT NULL
	DROP TABLE [dbo].[CrArMst];

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CrArMst](
	[id] [varchar](40) NOT NULL,
	[ArMstId] [int] NULL,
	[CrMid] [varchar](50) NULL,
	[CrDid] [varchar](50) NULL,
 CONSTRAINT [PK_CRArMst] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
