<?xml version="1.0" encoding="utf-8"?><Database Name="testdb" Class="DbClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=df2a\sqlexpress;Initial Catalog=testdb;Integrated Security=True" SettingsObjectName="dataLib.Properties.Settings" SettingsPropertyName="testdbConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CRMasterId" Member="CRMasterIds">
    <Type Name="CRMasterId">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RcptId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CRAccount" Member="CRAccounts">
    <Type Name="CRAccount">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AccountName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AccountNoInt" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NAME" Member="NAMEs">
    <Type Name="NAME">
      <Column Name="NAME_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="DBA" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Phone_Ext" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Cell" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Other_Phone" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Other_Ext" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UseStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RecForm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurFormOnFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateLastForm" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameType" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="RRAStatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AcresInFedDistricts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MultiDistrict" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Citizenship" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TypeOtherDesc" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Resident" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PENALTYMULTIPLIER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CountyRecord" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="SubOfName" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserChanged" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LastPenaltyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EntityLink" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRDetail" Member="CRDetails">
    <Type Name="CRDetail">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CRMid" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Account" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Note" Type="System.String" DbType="VarChar(80)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.v_CrReceipt" Member="v_CrReceipts">
    <Type Name="v_CrReceipt">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mPayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mPayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mPayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mnote" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="dAccount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dnote" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CMContact" Member="CMContacts">
    <Type Name="CMContact">
      <Column Name="IDContact" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PNL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CMEmail" Member="CMEmails">
    <Type Name="CMEmail">
      <Column Name="IDEmail" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CMNameContact" Member="CMNameContacts">
    <Type Name="CMNameContact">
      <Column Name="IDNameCont" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Name_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDContact" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Type" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="IDAddress" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="IDPhone" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="IDEmail" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Prim" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AP" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Other" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRDepItem" Member="CRDepItems">
    <Type Name="CRDepItem">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDBatch" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CRMid" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Armst" Member="Armsts">
    <Type Name="Armst">
      <Column Name="ARMSTID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BatchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="VarChar(35)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Invoice_NO" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BillingType_ID" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TransType" Type="System.String" DbType="VarChar(3)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ActionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DepositDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="xperiodunused" Type="System.String" DbType="Char(4)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PeriodFromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PeriodToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Posted" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrigAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CurrAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AppliedAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserChanged" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Reference" Type="System.String" DbType="VarChar(22)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RefType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ReceiptID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditApplied" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditArMstId" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noshow" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DueDate2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Credit_DB" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Credit_CR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Period" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TempCode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RRevInuse" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RRevDone" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pastdue_flag" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pastdue_amt" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="penalty_Armstid" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="penalty_charged" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Armst_ArDtl" Member="ArDtls" ThisKey="ARMSTID" OtherKey="ARMSTID" Type="ArDtl" />
    </Type>
  </Table>
  <Table Name="dbo.ArDtl" Member="ArDtls">
    <Type Name="ArDtl">
      <Column Name="TranId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ARMSTID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RelatedTranId" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Invoice_NO" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name_Id" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ActionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BillingType_ID" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="VarChar(5)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UnitAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrigAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CurrAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AppliedAmount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Turnout_Id" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Field_Id" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WaterCatagory_Id" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WaterRate_Id" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Parcel_Id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Assessment_Id" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RLUID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Acres" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CASH_CR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CASH_DB" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BILL_DB" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BILL_CR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserChanged" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Code_ID" Type="System.String" DbType="VarChar(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditApplied" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditArMstId" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TransType" Type="System.String" DbType="VarChar(3)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NoShow" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Posted" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PenaltyCharged" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Percent]" Member="Percent" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Liened" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ExportBatchID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pi_amt" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pastdue_amt" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Round_Method" Type="System.String" DbType="VarChar(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Round_Rate" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Round_Qty" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RateBatchID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Armst_ArDtl" Member="Armst" ThisKey="ARMSTID" OtherKey="ARMSTID" Type="Armst" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CROutstanding" Member="CROutstandings">
    <Type Name="CROutstanding">
      <Column Name="ItemGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TranType" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Invoice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Session" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblLog" Member="TblLogs">
    <Type Name="TblLog">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tblName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tblId" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="cdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cuser" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="txt" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRMaster" Member="CRMasters">
    <Type Name="CRMaster">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StateRcv" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StateGA" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StateAR" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RcptID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Note" Type="System.String" DbType="VarChar(80)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Postmark" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.v_CrDepositBatch" Member="v_CrDepositBatches">
    <Type Name="v_CrDepositBatch">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="IDBank" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepositAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PaymentAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RcptID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_TestData1" Member="v_TestData1s">
    <Type Name="v_TestData1">
      <Column Name="account" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="VarChar(38)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRDepBatch" Member="CRDepBatches">
    <Type Name="CRDepBatch">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IDBank" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DepositDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CrArMst" Member="CrArMsts">
    <Type Name="CrArMst">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArMstId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CrMid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CrDid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRPaymentInfo" Member="CRPaymentInfos">
    <Type Name="CRPaymentInfo">
      <Column Name="RcptID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RcvState" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Postmark" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BankBatch" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GAState" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DepositAmount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DepositDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StateAR" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Outstanding" Method="sp_Outstanding">
    <Parameter Name="Account" Parameter="account" Type="System.Int32" DbType="Int" />
    <Parameter Name="Session" Parameter="session" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>