<?xml version="1.0" encoding="utf-8"?><Database Name="testdb" Class="dbClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=testdb;Integrated Security=True" SettingsObjectName="dataLib.Properties.Settings" SettingsPropertyName="testdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CRMasterId" Member="CRMasterIds">
    <Type Name="CRMasterId">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RcptId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CRMaster" Member="CRMasters">
    <Type Name="CRMaster">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RcptID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Note" Type="System.String" DbType="VarChar(80)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CDate" AutoSync="OnUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" AutoSync="OnUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UDate" AutoSync="OnUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UUser" AutoSync="OnUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CRAccount" Member="CRAccounts">
    <Type Name="CRAccount">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AccountName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AccountNoInt" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NAME" Member="NAMEs">
    <Type Name="NAME">
      <Column Name="NAME_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="DBA" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Phone_Ext" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Cell" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Other_Phone" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Other_Ext" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UseStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RecForm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurFormOnFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateLastForm" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameType" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="RRAStatus" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AcresInFedDistricts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MultiDistrict" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Citizenship" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TypeOtherDesc" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Resident" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PENALTYMULTIPLIER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CountyRecord" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="SubOfName" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserChanged" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LastPenaltyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EntityLink" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRDetail" Member="CRDetails">
    <Type Name="CRDetail">
      <Column Name="Id" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CRMid" Type="System.String" DbType="VarChar(40)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Account" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Note" Type="System.String" DbType="VarChar(80)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.v_CrReceipt" Member="v_CrReceipts">
    <Type Name="v_CrReceipt">
      <Column Name="id" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mPayRef" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mPayType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mPayVia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mnote" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="dAccount" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dnote" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
</Database>