#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mas500_Development_app")]
	public partial class m500ClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttarCustomer(tarCustomer instance);
    partial void UpdatetarCustomer(tarCustomer instance);
    partial void DeletetarCustomer(tarCustomer instance);
    partial void InserttarInvoice(tarInvoice instance);
    partial void UpdatetarInvoice(tarInvoice instance);
    partial void DeletetarInvoice(tarInvoice instance);
    #endregion
		
		public m500ClassDataContext() : 
				base(global::dataLib.Properties.Settings.Default.mas500_Development_appConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tarCustomer> tarCustomers
		{
			get
			{
				return this.GetTable<tarCustomer>();
			}
		}
		
		public System.Data.Linq.Table<tarInvoice> tarInvoices
		{
			get
			{
				return this.GetTable<tarInvoice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tarCustomer")]
	public partial class tarCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustKey;
		
		private string _ABANo;
		
		private short _AllowCustRefund;
		
		private short _AllowWriteOff;
		
		private short _BillingType;
		
		private short _BillToNationalAcctParent;
		
		private string _CompanyID;
		
		private short _ConsolidatedStatement;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private short _CreateType;
		
		private string _CreateUserID;
		
		private decimal _CreditLimit;
		
		private short _CreditLimitAgeCat;
		
		private short _CreditLimitUsed;
		
		private string _CRMCustID;
		
		private System.Nullable<int> _CurrExchSchdKey;
		
		private int _CustClassKey;
		
		private string _CustID;
		
		private string _CustName;
		
		private string _CustRefNo;
		
		private System.Nullable<System.DateTime> _DateEstab;
		
		private int _DfltBillToAddrKey;
		
		private System.Nullable<int> _DfltItemKey;
		
		private System.Nullable<int> _DfltSalesAcctKey;
		
		private System.Nullable<int> _DfltSalesReturnAcctKey;
		
		private int _DfltShipToAddrKey;
		
		private decimal _FinChgFlatAmt;
		
		private System.Nullable<decimal> _FinChgPct;
		
		private short _Hold;
		
		private System.Nullable<int> _ImportLogKey;
		
		private System.Nullable<int> _NationalAcctLevelKey;
		
		private short _PmtByNationalAcctParent;
		
		private int _PrimaryAddrKey;
		
		private System.Nullable<int> _PrimaryCntctKey;
		
		private short _PrintDunnMsg;
		
		private System.Nullable<decimal> _ReqCreditLimit;
		
		private short _ReqPO;
		
		private System.Nullable<decimal> _RetntPct;
		
		private System.Nullable<int> _SalesSourceKey;
		
		private short _ShipPriority;
		
		private short _Status;
		
		private string _StdIndusCodeID;
		
		private System.Nullable<int> _StmtCycleKey;
		
		private System.Nullable<int> _StmtFormKey;
		
		private System.Nullable<decimal> _TradeDiscPct;
		
		private int _UpdateCounter;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _UpdateUserID;
		
		private string _UserFld1;
		
		private string _UserFld2;
		
		private string _UserFld3;
		
		private string _UserFld4;
		
		private System.Nullable<int> _VendKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustKeyChanging(int value);
    partial void OnCustKeyChanged();
    partial void OnABANoChanging(string value);
    partial void OnABANoChanged();
    partial void OnAllowCustRefundChanging(short value);
    partial void OnAllowCustRefundChanged();
    partial void OnAllowWriteOffChanging(short value);
    partial void OnAllowWriteOffChanged();
    partial void OnBillingTypeChanging(short value);
    partial void OnBillingTypeChanged();
    partial void OnBillToNationalAcctParentChanging(short value);
    partial void OnBillToNationalAcctParentChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnConsolidatedStatementChanging(short value);
    partial void OnConsolidatedStatementChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateTypeChanging(short value);
    partial void OnCreateTypeChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCreditLimitChanging(decimal value);
    partial void OnCreditLimitChanged();
    partial void OnCreditLimitAgeCatChanging(short value);
    partial void OnCreditLimitAgeCatChanged();
    partial void OnCreditLimitUsedChanging(short value);
    partial void OnCreditLimitUsedChanged();
    partial void OnCRMCustIDChanging(string value);
    partial void OnCRMCustIDChanged();
    partial void OnCurrExchSchdKeyChanging(System.Nullable<int> value);
    partial void OnCurrExchSchdKeyChanged();
    partial void OnCustClassKeyChanging(int value);
    partial void OnCustClassKeyChanged();
    partial void OnCustIDChanging(string value);
    partial void OnCustIDChanged();
    partial void OnCustNameChanging(string value);
    partial void OnCustNameChanged();
    partial void OnCustRefNoChanging(string value);
    partial void OnCustRefNoChanged();
    partial void OnDateEstabChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEstabChanged();
    partial void OnDfltBillToAddrKeyChanging(int value);
    partial void OnDfltBillToAddrKeyChanged();
    partial void OnDfltItemKeyChanging(System.Nullable<int> value);
    partial void OnDfltItemKeyChanged();
    partial void OnDfltSalesAcctKeyChanging(System.Nullable<int> value);
    partial void OnDfltSalesAcctKeyChanged();
    partial void OnDfltSalesReturnAcctKeyChanging(System.Nullable<int> value);
    partial void OnDfltSalesReturnAcctKeyChanged();
    partial void OnDfltShipToAddrKeyChanging(int value);
    partial void OnDfltShipToAddrKeyChanged();
    partial void OnFinChgFlatAmtChanging(decimal value);
    partial void OnFinChgFlatAmtChanged();
    partial void OnFinChgPctChanging(System.Nullable<decimal> value);
    partial void OnFinChgPctChanged();
    partial void OnHoldChanging(short value);
    partial void OnHoldChanged();
    partial void OnImportLogKeyChanging(System.Nullable<int> value);
    partial void OnImportLogKeyChanged();
    partial void OnNationalAcctLevelKeyChanging(System.Nullable<int> value);
    partial void OnNationalAcctLevelKeyChanged();
    partial void OnPmtByNationalAcctParentChanging(short value);
    partial void OnPmtByNationalAcctParentChanged();
    partial void OnPrimaryAddrKeyChanging(int value);
    partial void OnPrimaryAddrKeyChanged();
    partial void OnPrimaryCntctKeyChanging(System.Nullable<int> value);
    partial void OnPrimaryCntctKeyChanged();
    partial void OnPrintDunnMsgChanging(short value);
    partial void OnPrintDunnMsgChanged();
    partial void OnReqCreditLimitChanging(System.Nullable<decimal> value);
    partial void OnReqCreditLimitChanged();
    partial void OnReqPOChanging(short value);
    partial void OnReqPOChanged();
    partial void OnRetntPctChanging(System.Nullable<decimal> value);
    partial void OnRetntPctChanged();
    partial void OnSalesSourceKeyChanging(System.Nullable<int> value);
    partial void OnSalesSourceKeyChanged();
    partial void OnShipPriorityChanging(short value);
    partial void OnShipPriorityChanged();
    partial void OnStatusChanging(short value);
    partial void OnStatusChanged();
    partial void OnStdIndusCodeIDChanging(string value);
    partial void OnStdIndusCodeIDChanged();
    partial void OnStmtCycleKeyChanging(System.Nullable<int> value);
    partial void OnStmtCycleKeyChanged();
    partial void OnStmtFormKeyChanging(System.Nullable<int> value);
    partial void OnStmtFormKeyChanged();
    partial void OnTradeDiscPctChanging(System.Nullable<decimal> value);
    partial void OnTradeDiscPctChanged();
    partial void OnUpdateCounterChanging(int value);
    partial void OnUpdateCounterChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateUserIDChanging(string value);
    partial void OnUpdateUserIDChanged();
    partial void OnUserFld1Changing(string value);
    partial void OnUserFld1Changed();
    partial void OnUserFld2Changing(string value);
    partial void OnUserFld2Changed();
    partial void OnUserFld3Changing(string value);
    partial void OnUserFld3Changed();
    partial void OnUserFld4Changing(string value);
    partial void OnUserFld4Changed();
    partial void OnVendKeyChanging(System.Nullable<int> value);
    partial void OnVendKeyChanged();
    #endregion
		
		public tarCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustKey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustKey
		{
			get
			{
				return this._CustKey;
			}
			set
			{
				if ((this._CustKey != value))
				{
					this.OnCustKeyChanging(value);
					this.SendPropertyChanging();
					this._CustKey = value;
					this.SendPropertyChanged("CustKey");
					this.OnCustKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABANo", DbType="VarChar(10)")]
		public string ABANo
		{
			get
			{
				return this._ABANo;
			}
			set
			{
				if ((this._ABANo != value))
				{
					this.OnABANoChanging(value);
					this.SendPropertyChanging();
					this._ABANo = value;
					this.SendPropertyChanged("ABANo");
					this.OnABANoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowCustRefund", DbType="SmallInt NOT NULL")]
		public short AllowCustRefund
		{
			get
			{
				return this._AllowCustRefund;
			}
			set
			{
				if ((this._AllowCustRefund != value))
				{
					this.OnAllowCustRefundChanging(value);
					this.SendPropertyChanging();
					this._AllowCustRefund = value;
					this.SendPropertyChanged("AllowCustRefund");
					this.OnAllowCustRefundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowWriteOff", DbType="SmallInt NOT NULL")]
		public short AllowWriteOff
		{
			get
			{
				return this._AllowWriteOff;
			}
			set
			{
				if ((this._AllowWriteOff != value))
				{
					this.OnAllowWriteOffChanging(value);
					this.SendPropertyChanging();
					this._AllowWriteOff = value;
					this.SendPropertyChanged("AllowWriteOff");
					this.OnAllowWriteOffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingType", DbType="SmallInt NOT NULL")]
		public short BillingType
		{
			get
			{
				return this._BillingType;
			}
			set
			{
				if ((this._BillingType != value))
				{
					this.OnBillingTypeChanging(value);
					this.SendPropertyChanging();
					this._BillingType = value;
					this.SendPropertyChanged("BillingType");
					this.OnBillingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToNationalAcctParent", DbType="SmallInt NOT NULL")]
		public short BillToNationalAcctParent
		{
			get
			{
				return this._BillToNationalAcctParent;
			}
			set
			{
				if ((this._BillToNationalAcctParent != value))
				{
					this.OnBillToNationalAcctParentChanging(value);
					this.SendPropertyChanging();
					this._BillToNationalAcctParent = value;
					this.SendPropertyChanged("BillToNationalAcctParent");
					this.OnBillToNationalAcctParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsolidatedStatement", DbType="SmallInt NOT NULL")]
		public short ConsolidatedStatement
		{
			get
			{
				return this._ConsolidatedStatement;
			}
			set
			{
				if ((this._ConsolidatedStatement != value))
				{
					this.OnConsolidatedStatementChanging(value);
					this.SendPropertyChanging();
					this._ConsolidatedStatement = value;
					this.SendPropertyChanged("ConsolidatedStatement");
					this.OnConsolidatedStatementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateType", DbType="SmallInt NOT NULL")]
		public short CreateType
		{
			get
			{
				return this._CreateType;
			}
			set
			{
				if ((this._CreateType != value))
				{
					this.OnCreateTypeChanging(value);
					this.SendPropertyChanging();
					this._CreateType = value;
					this.SendPropertyChanged("CreateType");
					this.OnCreateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="VarChar(30)")]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Decimal(12,0) NOT NULL")]
		public decimal CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this.OnCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._CreditLimit = value;
					this.SendPropertyChanged("CreditLimit");
					this.OnCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitAgeCat", DbType="SmallInt NOT NULL")]
		public short CreditLimitAgeCat
		{
			get
			{
				return this._CreditLimitAgeCat;
			}
			set
			{
				if ((this._CreditLimitAgeCat != value))
				{
					this.OnCreditLimitAgeCatChanging(value);
					this.SendPropertyChanging();
					this._CreditLimitAgeCat = value;
					this.SendPropertyChanged("CreditLimitAgeCat");
					this.OnCreditLimitAgeCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitUsed", DbType="SmallInt NOT NULL")]
		public short CreditLimitUsed
		{
			get
			{
				return this._CreditLimitUsed;
			}
			set
			{
				if ((this._CreditLimitUsed != value))
				{
					this.OnCreditLimitUsedChanging(value);
					this.SendPropertyChanging();
					this._CreditLimitUsed = value;
					this.SendPropertyChanged("CreditLimitUsed");
					this.OnCreditLimitUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRMCustID", DbType="VarChar(32)")]
		public string CRMCustID
		{
			get
			{
				return this._CRMCustID;
			}
			set
			{
				if ((this._CRMCustID != value))
				{
					this.OnCRMCustIDChanging(value);
					this.SendPropertyChanging();
					this._CRMCustID = value;
					this.SendPropertyChanged("CRMCustID");
					this.OnCRMCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrExchSchdKey", DbType="Int")]
		public System.Nullable<int> CurrExchSchdKey
		{
			get
			{
				return this._CurrExchSchdKey;
			}
			set
			{
				if ((this._CurrExchSchdKey != value))
				{
					this.OnCurrExchSchdKeyChanging(value);
					this.SendPropertyChanging();
					this._CurrExchSchdKey = value;
					this.SendPropertyChanged("CurrExchSchdKey");
					this.OnCurrExchSchdKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustClassKey", DbType="Int NOT NULL")]
		public int CustClassKey
		{
			get
			{
				return this._CustClassKey;
			}
			set
			{
				if ((this._CustClassKey != value))
				{
					this.OnCustClassKeyChanging(value);
					this.SendPropertyChanging();
					this._CustClassKey = value;
					this.SendPropertyChanged("CustClassKey");
					this.OnCustClassKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string CustName
		{
			get
			{
				return this._CustName;
			}
			set
			{
				if ((this._CustName != value))
				{
					this.OnCustNameChanging(value);
					this.SendPropertyChanging();
					this._CustName = value;
					this.SendPropertyChanged("CustName");
					this.OnCustNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustRefNo", DbType="VarChar(15)")]
		public string CustRefNo
		{
			get
			{
				return this._CustRefNo;
			}
			set
			{
				if ((this._CustRefNo != value))
				{
					this.OnCustRefNoChanging(value);
					this.SendPropertyChanging();
					this._CustRefNo = value;
					this.SendPropertyChanged("CustRefNo");
					this.OnCustRefNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEstab", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEstab
		{
			get
			{
				return this._DateEstab;
			}
			set
			{
				if ((this._DateEstab != value))
				{
					this.OnDateEstabChanging(value);
					this.SendPropertyChanging();
					this._DateEstab = value;
					this.SendPropertyChanged("DateEstab");
					this.OnDateEstabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltBillToAddrKey", DbType="Int NOT NULL")]
		public int DfltBillToAddrKey
		{
			get
			{
				return this._DfltBillToAddrKey;
			}
			set
			{
				if ((this._DfltBillToAddrKey != value))
				{
					this.OnDfltBillToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltBillToAddrKey = value;
					this.SendPropertyChanged("DfltBillToAddrKey");
					this.OnDfltBillToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltItemKey", DbType="Int")]
		public System.Nullable<int> DfltItemKey
		{
			get
			{
				return this._DfltItemKey;
			}
			set
			{
				if ((this._DfltItemKey != value))
				{
					this.OnDfltItemKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltItemKey = value;
					this.SendPropertyChanged("DfltItemKey");
					this.OnDfltItemKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltSalesAcctKey", DbType="Int")]
		public System.Nullable<int> DfltSalesAcctKey
		{
			get
			{
				return this._DfltSalesAcctKey;
			}
			set
			{
				if ((this._DfltSalesAcctKey != value))
				{
					this.OnDfltSalesAcctKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltSalesAcctKey = value;
					this.SendPropertyChanged("DfltSalesAcctKey");
					this.OnDfltSalesAcctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltSalesReturnAcctKey", DbType="Int")]
		public System.Nullable<int> DfltSalesReturnAcctKey
		{
			get
			{
				return this._DfltSalesReturnAcctKey;
			}
			set
			{
				if ((this._DfltSalesReturnAcctKey != value))
				{
					this.OnDfltSalesReturnAcctKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltSalesReturnAcctKey = value;
					this.SendPropertyChanged("DfltSalesReturnAcctKey");
					this.OnDfltSalesReturnAcctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltShipToAddrKey", DbType="Int NOT NULL")]
		public int DfltShipToAddrKey
		{
			get
			{
				return this._DfltShipToAddrKey;
			}
			set
			{
				if ((this._DfltShipToAddrKey != value))
				{
					this.OnDfltShipToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltShipToAddrKey = value;
					this.SendPropertyChanged("DfltShipToAddrKey");
					this.OnDfltShipToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChgFlatAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal FinChgFlatAmt
		{
			get
			{
				return this._FinChgFlatAmt;
			}
			set
			{
				if ((this._FinChgFlatAmt != value))
				{
					this.OnFinChgFlatAmtChanging(value);
					this.SendPropertyChanging();
					this._FinChgFlatAmt = value;
					this.SendPropertyChanged("FinChgFlatAmt");
					this.OnFinChgFlatAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChgPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> FinChgPct
		{
			get
			{
				return this._FinChgPct;
			}
			set
			{
				if ((this._FinChgPct != value))
				{
					this.OnFinChgPctChanging(value);
					this.SendPropertyChanging();
					this._FinChgPct = value;
					this.SendPropertyChanged("FinChgPct");
					this.OnFinChgPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hold", DbType="SmallInt NOT NULL")]
		public short Hold
		{
			get
			{
				return this._Hold;
			}
			set
			{
				if ((this._Hold != value))
				{
					this.OnHoldChanging(value);
					this.SendPropertyChanging();
					this._Hold = value;
					this.SendPropertyChanged("Hold");
					this.OnHoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportLogKey", DbType="Int")]
		public System.Nullable<int> ImportLogKey
		{
			get
			{
				return this._ImportLogKey;
			}
			set
			{
				if ((this._ImportLogKey != value))
				{
					this.OnImportLogKeyChanging(value);
					this.SendPropertyChanging();
					this._ImportLogKey = value;
					this.SendPropertyChanged("ImportLogKey");
					this.OnImportLogKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalAcctLevelKey", DbType="Int")]
		public System.Nullable<int> NationalAcctLevelKey
		{
			get
			{
				return this._NationalAcctLevelKey;
			}
			set
			{
				if ((this._NationalAcctLevelKey != value))
				{
					this.OnNationalAcctLevelKeyChanging(value);
					this.SendPropertyChanging();
					this._NationalAcctLevelKey = value;
					this.SendPropertyChanged("NationalAcctLevelKey");
					this.OnNationalAcctLevelKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PmtByNationalAcctParent", DbType="SmallInt NOT NULL")]
		public short PmtByNationalAcctParent
		{
			get
			{
				return this._PmtByNationalAcctParent;
			}
			set
			{
				if ((this._PmtByNationalAcctParent != value))
				{
					this.OnPmtByNationalAcctParentChanging(value);
					this.SendPropertyChanging();
					this._PmtByNationalAcctParent = value;
					this.SendPropertyChanged("PmtByNationalAcctParent");
					this.OnPmtByNationalAcctParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddrKey", DbType="Int NOT NULL")]
		public int PrimaryAddrKey
		{
			get
			{
				return this._PrimaryAddrKey;
			}
			set
			{
				if ((this._PrimaryAddrKey != value))
				{
					this.OnPrimaryAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimaryAddrKey = value;
					this.SendPropertyChanged("PrimaryAddrKey");
					this.OnPrimaryAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCntctKey", DbType="Int")]
		public System.Nullable<int> PrimaryCntctKey
		{
			get
			{
				return this._PrimaryCntctKey;
			}
			set
			{
				if ((this._PrimaryCntctKey != value))
				{
					this.OnPrimaryCntctKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCntctKey = value;
					this.SendPropertyChanged("PrimaryCntctKey");
					this.OnPrimaryCntctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintDunnMsg", DbType="SmallInt NOT NULL")]
		public short PrintDunnMsg
		{
			get
			{
				return this._PrintDunnMsg;
			}
			set
			{
				if ((this._PrintDunnMsg != value))
				{
					this.OnPrintDunnMsgChanging(value);
					this.SendPropertyChanging();
					this._PrintDunnMsg = value;
					this.SendPropertyChanged("PrintDunnMsg");
					this.OnPrintDunnMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqCreditLimit", DbType="Decimal(15,3)")]
		public System.Nullable<decimal> ReqCreditLimit
		{
			get
			{
				return this._ReqCreditLimit;
			}
			set
			{
				if ((this._ReqCreditLimit != value))
				{
					this.OnReqCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._ReqCreditLimit = value;
					this.SendPropertyChanged("ReqCreditLimit");
					this.OnReqCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqPO", DbType="SmallInt NOT NULL")]
		public short ReqPO
		{
			get
			{
				return this._ReqPO;
			}
			set
			{
				if ((this._ReqPO != value))
				{
					this.OnReqPOChanging(value);
					this.SendPropertyChanging();
					this._ReqPO = value;
					this.SendPropertyChanged("ReqPO");
					this.OnReqPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetntPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> RetntPct
		{
			get
			{
				return this._RetntPct;
			}
			set
			{
				if ((this._RetntPct != value))
				{
					this.OnRetntPctChanging(value);
					this.SendPropertyChanging();
					this._RetntPct = value;
					this.SendPropertyChanged("RetntPct");
					this.OnRetntPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesSourceKey", DbType="Int")]
		public System.Nullable<int> SalesSourceKey
		{
			get
			{
				return this._SalesSourceKey;
			}
			set
			{
				if ((this._SalesSourceKey != value))
				{
					this.OnSalesSourceKeyChanging(value);
					this.SendPropertyChanging();
					this._SalesSourceKey = value;
					this.SendPropertyChanged("SalesSourceKey");
					this.OnSalesSourceKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPriority", DbType="SmallInt NOT NULL")]
		public short ShipPriority
		{
			get
			{
				return this._ShipPriority;
			}
			set
			{
				if ((this._ShipPriority != value))
				{
					this.OnShipPriorityChanging(value);
					this.SendPropertyChanging();
					this._ShipPriority = value;
					this.SendPropertyChanged("ShipPriority");
					this.OnShipPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt NOT NULL")]
		public short Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdIndusCodeID", DbType="VarChar(7)")]
		public string StdIndusCodeID
		{
			get
			{
				return this._StdIndusCodeID;
			}
			set
			{
				if ((this._StdIndusCodeID != value))
				{
					this.OnStdIndusCodeIDChanging(value);
					this.SendPropertyChanging();
					this._StdIndusCodeID = value;
					this.SendPropertyChanged("StdIndusCodeID");
					this.OnStdIndusCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtCycleKey", DbType="Int")]
		public System.Nullable<int> StmtCycleKey
		{
			get
			{
				return this._StmtCycleKey;
			}
			set
			{
				if ((this._StmtCycleKey != value))
				{
					this.OnStmtCycleKeyChanging(value);
					this.SendPropertyChanging();
					this._StmtCycleKey = value;
					this.SendPropertyChanged("StmtCycleKey");
					this.OnStmtCycleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtFormKey", DbType="Int")]
		public System.Nullable<int> StmtFormKey
		{
			get
			{
				return this._StmtFormKey;
			}
			set
			{
				if ((this._StmtFormKey != value))
				{
					this.OnStmtFormKeyChanging(value);
					this.SendPropertyChanging();
					this._StmtFormKey = value;
					this.SendPropertyChanged("StmtFormKey");
					this.OnStmtFormKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeDiscPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> TradeDiscPct
		{
			get
			{
				return this._TradeDiscPct;
			}
			set
			{
				if ((this._TradeDiscPct != value))
				{
					this.OnTradeDiscPctChanging(value);
					this.SendPropertyChanging();
					this._TradeDiscPct = value;
					this.SendPropertyChanged("TradeDiscPct");
					this.OnTradeDiscPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateCounter", DbType="Int NOT NULL")]
		public int UpdateCounter
		{
			get
			{
				return this._UpdateCounter;
			}
			set
			{
				if ((this._UpdateCounter != value))
				{
					this.OnUpdateCounterChanging(value);
					this.SendPropertyChanging();
					this._UpdateCounter = value;
					this.SendPropertyChanged("UpdateCounter");
					this.OnUpdateCounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUserID", DbType="VarChar(30)")]
		public string UpdateUserID
		{
			get
			{
				return this._UpdateUserID;
			}
			set
			{
				if ((this._UpdateUserID != value))
				{
					this.OnUpdateUserIDChanging(value);
					this.SendPropertyChanging();
					this._UpdateUserID = value;
					this.SendPropertyChanged("UpdateUserID");
					this.OnUpdateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld1", DbType="VarChar(15)")]
		public string UserFld1
		{
			get
			{
				return this._UserFld1;
			}
			set
			{
				if ((this._UserFld1 != value))
				{
					this.OnUserFld1Changing(value);
					this.SendPropertyChanging();
					this._UserFld1 = value;
					this.SendPropertyChanged("UserFld1");
					this.OnUserFld1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld2", DbType="VarChar(15)")]
		public string UserFld2
		{
			get
			{
				return this._UserFld2;
			}
			set
			{
				if ((this._UserFld2 != value))
				{
					this.OnUserFld2Changing(value);
					this.SendPropertyChanging();
					this._UserFld2 = value;
					this.SendPropertyChanged("UserFld2");
					this.OnUserFld2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld3", DbType="VarChar(15)")]
		public string UserFld3
		{
			get
			{
				return this._UserFld3;
			}
			set
			{
				if ((this._UserFld3 != value))
				{
					this.OnUserFld3Changing(value);
					this.SendPropertyChanging();
					this._UserFld3 = value;
					this.SendPropertyChanged("UserFld3");
					this.OnUserFld3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld4", DbType="VarChar(15)")]
		public string UserFld4
		{
			get
			{
				return this._UserFld4;
			}
			set
			{
				if ((this._UserFld4 != value))
				{
					this.OnUserFld4Changing(value);
					this.SendPropertyChanging();
					this._UserFld4 = value;
					this.SendPropertyChanged("UserFld4");
					this.OnUserFld4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendKey", DbType="Int")]
		public System.Nullable<int> VendKey
		{
			get
			{
				return this._VendKey;
			}
			set
			{
				if ((this._VendKey != value))
				{
					this.OnVendKeyChanging(value);
					this.SendPropertyChanging();
					this._VendKey = value;
					this.SendPropertyChanged("VendKey");
					this.OnVendKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tarInvoice")]
	public partial class tarInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InvcKey;
		
		private decimal _AuthOvrdAmt;
		
		private decimal _Balance;
		
		private decimal _BalanceHC;
		
		private int _BatchKey;
		
		private int _BillToAddrKey;
		
		private System.Nullable<int> _BillToCustAddrKey;
		
		private System.Nullable<System.DateTime> _ClosingPostDate;
		
		private System.Nullable<System.DateTime> _ClosingTranDate;
		
		private System.Nullable<int> _CommPlanKey;
		
		private string _CompanyID;
		
		private System.Nullable<int> _ConfirmToCntctKey;
		
		private decimal _CostOfSales;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private short _CreateType;
		
		private string _CreateUserID;
		
		private double _CurrExchRate;
		
		private System.Nullable<int> _CurrExchSchdKey;
		
		private string _CurrID;
		
		private int _CustClassKey;
		
		private int _CustKey;
		
		private string _CustPONo;
		
		private decimal _DiscAmt;
		
		private System.Nullable<System.DateTime> _DiscDate;
		
		private decimal _DiscTakenAmt;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private System.Nullable<int> _FOBKey;
		
		private decimal _HandlAmt;
		
		private System.Nullable<int> _ImportLogKey;
		
		private short _InDispute;
		
		private System.Nullable<int> _InvcFormKey;
		
		private System.Nullable<int> _NextApplEntryNo;
		
		private System.Nullable<int> _PmtTermsKey;
		
		private System.DateTime _PostDate;
		
		private System.Nullable<int> _PrimarySperKey;
		
		private short _Printed;
		
		private System.Nullable<int> _ReasonCodeKey;
		
		private System.Nullable<int> _RecurInvoiceKey;
		
		private decimal _RetntAmt;
		
		private System.Nullable<decimal> _RetntPct;
		
		private decimal _SalesAmt;
		
		private decimal _ShipAmt;
		
		private System.Nullable<int> _ShipMethKey;
		
		private int _ShipToAddrKey;
		
		private System.Nullable<int> _ShipToCustAddrKey;
		
		private System.Nullable<int> _ShipZoneKey;
		
		private short _SourceModule;
		
		private short _Status;
		
		private decimal _STaxAmt;
		
		private short _STaxCalc;
		
		private System.Nullable<int> _STaxTranKey;
		
		private decimal _TradeDiscAmt;
		
		private decimal _TranAmt;
		
		private decimal _TranAmtHC;
		
		private string _TranCmnt;
		
		private System.DateTime _TranDate;
		
		private string _TranID;
		
		private string _TranNo;
		
		private int _TranType;
		
		private int _UpdateCounter;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _UpdateUserID;
		
		private System.Nullable<int> _VoucherKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvcKeyChanging(int value);
    partial void OnInvcKeyChanged();
    partial void OnAuthOvrdAmtChanging(decimal value);
    partial void OnAuthOvrdAmtChanged();
    partial void OnBalanceChanging(decimal value);
    partial void OnBalanceChanged();
    partial void OnBalanceHCChanging(decimal value);
    partial void OnBalanceHCChanged();
    partial void OnBatchKeyChanging(int value);
    partial void OnBatchKeyChanged();
    partial void OnBillToAddrKeyChanging(int value);
    partial void OnBillToAddrKeyChanged();
    partial void OnBillToCustAddrKeyChanging(System.Nullable<int> value);
    partial void OnBillToCustAddrKeyChanged();
    partial void OnClosingPostDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClosingPostDateChanged();
    partial void OnClosingTranDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClosingTranDateChanged();
    partial void OnCommPlanKeyChanging(System.Nullable<int> value);
    partial void OnCommPlanKeyChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnConfirmToCntctKeyChanging(System.Nullable<int> value);
    partial void OnConfirmToCntctKeyChanged();
    partial void OnCostOfSalesChanging(decimal value);
    partial void OnCostOfSalesChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateTypeChanging(short value);
    partial void OnCreateTypeChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCurrExchRateChanging(double value);
    partial void OnCurrExchRateChanged();
    partial void OnCurrExchSchdKeyChanging(System.Nullable<int> value);
    partial void OnCurrExchSchdKeyChanged();
    partial void OnCurrIDChanging(string value);
    partial void OnCurrIDChanged();
    partial void OnCustClassKeyChanging(int value);
    partial void OnCustClassKeyChanged();
    partial void OnCustKeyChanging(int value);
    partial void OnCustKeyChanged();
    partial void OnCustPONoChanging(string value);
    partial void OnCustPONoChanged();
    partial void OnDiscAmtChanging(decimal value);
    partial void OnDiscAmtChanged();
    partial void OnDiscDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDiscDateChanged();
    partial void OnDiscTakenAmtChanging(decimal value);
    partial void OnDiscTakenAmtChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnFOBKeyChanging(System.Nullable<int> value);
    partial void OnFOBKeyChanged();
    partial void OnHandlAmtChanging(decimal value);
    partial void OnHandlAmtChanged();
    partial void OnImportLogKeyChanging(System.Nullable<int> value);
    partial void OnImportLogKeyChanged();
    partial void OnInDisputeChanging(short value);
    partial void OnInDisputeChanged();
    partial void OnInvcFormKeyChanging(System.Nullable<int> value);
    partial void OnInvcFormKeyChanged();
    partial void OnNextApplEntryNoChanging(System.Nullable<int> value);
    partial void OnNextApplEntryNoChanged();
    partial void OnPmtTermsKeyChanging(System.Nullable<int> value);
    partial void OnPmtTermsKeyChanged();
    partial void OnPostDateChanging(System.DateTime value);
    partial void OnPostDateChanged();
    partial void OnPrimarySperKeyChanging(System.Nullable<int> value);
    partial void OnPrimarySperKeyChanged();
    partial void OnPrintedChanging(short value);
    partial void OnPrintedChanged();
    partial void OnReasonCodeKeyChanging(System.Nullable<int> value);
    partial void OnReasonCodeKeyChanged();
    partial void OnRecurInvoiceKeyChanging(System.Nullable<int> value);
    partial void OnRecurInvoiceKeyChanged();
    partial void OnRetntAmtChanging(decimal value);
    partial void OnRetntAmtChanged();
    partial void OnRetntPctChanging(System.Nullable<decimal> value);
    partial void OnRetntPctChanged();
    partial void OnSalesAmtChanging(decimal value);
    partial void OnSalesAmtChanged();
    partial void OnShipAmtChanging(decimal value);
    partial void OnShipAmtChanged();
    partial void OnShipMethKeyChanging(System.Nullable<int> value);
    partial void OnShipMethKeyChanged();
    partial void OnShipToAddrKeyChanging(int value);
    partial void OnShipToAddrKeyChanged();
    partial void OnShipToCustAddrKeyChanging(System.Nullable<int> value);
    partial void OnShipToCustAddrKeyChanged();
    partial void OnShipZoneKeyChanging(System.Nullable<int> value);
    partial void OnShipZoneKeyChanged();
    partial void OnSourceModuleChanging(short value);
    partial void OnSourceModuleChanged();
    partial void OnStatusChanging(short value);
    partial void OnStatusChanged();
    partial void OnSTaxAmtChanging(decimal value);
    partial void OnSTaxAmtChanged();
    partial void OnSTaxCalcChanging(short value);
    partial void OnSTaxCalcChanged();
    partial void OnSTaxTranKeyChanging(System.Nullable<int> value);
    partial void OnSTaxTranKeyChanged();
    partial void OnTradeDiscAmtChanging(decimal value);
    partial void OnTradeDiscAmtChanged();
    partial void OnTranAmtChanging(decimal value);
    partial void OnTranAmtChanged();
    partial void OnTranAmtHCChanging(decimal value);
    partial void OnTranAmtHCChanged();
    partial void OnTranCmntChanging(string value);
    partial void OnTranCmntChanged();
    partial void OnTranDateChanging(System.DateTime value);
    partial void OnTranDateChanged();
    partial void OnTranIDChanging(string value);
    partial void OnTranIDChanged();
    partial void OnTranNoChanging(string value);
    partial void OnTranNoChanged();
    partial void OnTranTypeChanging(int value);
    partial void OnTranTypeChanged();
    partial void OnUpdateCounterChanging(int value);
    partial void OnUpdateCounterChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateUserIDChanging(string value);
    partial void OnUpdateUserIDChanged();
    partial void OnVoucherKeyChanging(System.Nullable<int> value);
    partial void OnVoucherKeyChanged();
    #endregion
		
		public tarInvoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvcKey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int InvcKey
		{
			get
			{
				return this._InvcKey;
			}
			set
			{
				if ((this._InvcKey != value))
				{
					this.OnInvcKeyChanging(value);
					this.SendPropertyChanging();
					this._InvcKey = value;
					this.SendPropertyChanged("InvcKey");
					this.OnInvcKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthOvrdAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal AuthOvrdAmt
		{
			get
			{
				return this._AuthOvrdAmt;
			}
			set
			{
				if ((this._AuthOvrdAmt != value))
				{
					this.OnAuthOvrdAmtChanging(value);
					this.SendPropertyChanging();
					this._AuthOvrdAmt = value;
					this.SendPropertyChanged("AuthOvrdAmt");
					this.OnAuthOvrdAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(15,3) NOT NULL")]
		public decimal Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceHC", DbType="Decimal(15,3) NOT NULL")]
		public decimal BalanceHC
		{
			get
			{
				return this._BalanceHC;
			}
			set
			{
				if ((this._BalanceHC != value))
				{
					this.OnBalanceHCChanging(value);
					this.SendPropertyChanging();
					this._BalanceHC = value;
					this.SendPropertyChanged("BalanceHC");
					this.OnBalanceHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchKey", DbType="Int NOT NULL")]
		public int BatchKey
		{
			get
			{
				return this._BatchKey;
			}
			set
			{
				if ((this._BatchKey != value))
				{
					this.OnBatchKeyChanging(value);
					this.SendPropertyChanging();
					this._BatchKey = value;
					this.SendPropertyChanged("BatchKey");
					this.OnBatchKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToAddrKey", DbType="Int NOT NULL")]
		public int BillToAddrKey
		{
			get
			{
				return this._BillToAddrKey;
			}
			set
			{
				if ((this._BillToAddrKey != value))
				{
					this.OnBillToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._BillToAddrKey = value;
					this.SendPropertyChanged("BillToAddrKey");
					this.OnBillToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToCustAddrKey", DbType="Int")]
		public System.Nullable<int> BillToCustAddrKey
		{
			get
			{
				return this._BillToCustAddrKey;
			}
			set
			{
				if ((this._BillToCustAddrKey != value))
				{
					this.OnBillToCustAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._BillToCustAddrKey = value;
					this.SendPropertyChanged("BillToCustAddrKey");
					this.OnBillToCustAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingPostDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosingPostDate
		{
			get
			{
				return this._ClosingPostDate;
			}
			set
			{
				if ((this._ClosingPostDate != value))
				{
					this.OnClosingPostDateChanging(value);
					this.SendPropertyChanging();
					this._ClosingPostDate = value;
					this.SendPropertyChanged("ClosingPostDate");
					this.OnClosingPostDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingTranDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosingTranDate
		{
			get
			{
				return this._ClosingTranDate;
			}
			set
			{
				if ((this._ClosingTranDate != value))
				{
					this.OnClosingTranDateChanging(value);
					this.SendPropertyChanging();
					this._ClosingTranDate = value;
					this.SendPropertyChanged("ClosingTranDate");
					this.OnClosingTranDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommPlanKey", DbType="Int")]
		public System.Nullable<int> CommPlanKey
		{
			get
			{
				return this._CommPlanKey;
			}
			set
			{
				if ((this._CommPlanKey != value))
				{
					this.OnCommPlanKeyChanging(value);
					this.SendPropertyChanging();
					this._CommPlanKey = value;
					this.SendPropertyChanged("CommPlanKey");
					this.OnCommPlanKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmToCntctKey", DbType="Int")]
		public System.Nullable<int> ConfirmToCntctKey
		{
			get
			{
				return this._ConfirmToCntctKey;
			}
			set
			{
				if ((this._ConfirmToCntctKey != value))
				{
					this.OnConfirmToCntctKeyChanging(value);
					this.SendPropertyChanging();
					this._ConfirmToCntctKey = value;
					this.SendPropertyChanged("ConfirmToCntctKey");
					this.OnConfirmToCntctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostOfSales", DbType="Decimal(15,3) NOT NULL")]
		public decimal CostOfSales
		{
			get
			{
				return this._CostOfSales;
			}
			set
			{
				if ((this._CostOfSales != value))
				{
					this.OnCostOfSalesChanging(value);
					this.SendPropertyChanging();
					this._CostOfSales = value;
					this.SendPropertyChanged("CostOfSales");
					this.OnCostOfSalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateType", DbType="SmallInt NOT NULL")]
		public short CreateType
		{
			get
			{
				return this._CreateType;
			}
			set
			{
				if ((this._CreateType != value))
				{
					this.OnCreateTypeChanging(value);
					this.SendPropertyChanging();
					this._CreateType = value;
					this.SendPropertyChanged("CreateType");
					this.OnCreateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="VarChar(30)")]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrExchRate", DbType="Float NOT NULL")]
		public double CurrExchRate
		{
			get
			{
				return this._CurrExchRate;
			}
			set
			{
				if ((this._CurrExchRate != value))
				{
					this.OnCurrExchRateChanging(value);
					this.SendPropertyChanging();
					this._CurrExchRate = value;
					this.SendPropertyChanged("CurrExchRate");
					this.OnCurrExchRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrExchSchdKey", DbType="Int")]
		public System.Nullable<int> CurrExchSchdKey
		{
			get
			{
				return this._CurrExchSchdKey;
			}
			set
			{
				if ((this._CurrExchSchdKey != value))
				{
					this.OnCurrExchSchdKeyChanging(value);
					this.SendPropertyChanging();
					this._CurrExchSchdKey = value;
					this.SendPropertyChanged("CurrExchSchdKey");
					this.OnCurrExchSchdKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CurrID
		{
			get
			{
				return this._CurrID;
			}
			set
			{
				if ((this._CurrID != value))
				{
					this.OnCurrIDChanging(value);
					this.SendPropertyChanging();
					this._CurrID = value;
					this.SendPropertyChanged("CurrID");
					this.OnCurrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustClassKey", DbType="Int NOT NULL")]
		public int CustClassKey
		{
			get
			{
				return this._CustClassKey;
			}
			set
			{
				if ((this._CustClassKey != value))
				{
					this.OnCustClassKeyChanging(value);
					this.SendPropertyChanging();
					this._CustClassKey = value;
					this.SendPropertyChanged("CustClassKey");
					this.OnCustClassKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustKey", DbType="Int NOT NULL")]
		public int CustKey
		{
			get
			{
				return this._CustKey;
			}
			set
			{
				if ((this._CustKey != value))
				{
					this.OnCustKeyChanging(value);
					this.SendPropertyChanging();
					this._CustKey = value;
					this.SendPropertyChanged("CustKey");
					this.OnCustKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustPONo", DbType="VarChar(15)")]
		public string CustPONo
		{
			get
			{
				return this._CustPONo;
			}
			set
			{
				if ((this._CustPONo != value))
				{
					this.OnCustPONoChanging(value);
					this.SendPropertyChanging();
					this._CustPONo = value;
					this.SendPropertyChanged("CustPONo");
					this.OnCustPONoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal DiscAmt
		{
			get
			{
				return this._DiscAmt;
			}
			set
			{
				if ((this._DiscAmt != value))
				{
					this.OnDiscAmtChanging(value);
					this.SendPropertyChanging();
					this._DiscAmt = value;
					this.SendPropertyChanged("DiscAmt");
					this.OnDiscAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DiscDate
		{
			get
			{
				return this._DiscDate;
			}
			set
			{
				if ((this._DiscDate != value))
				{
					this.OnDiscDateChanging(value);
					this.SendPropertyChanging();
					this._DiscDate = value;
					this.SendPropertyChanged("DiscDate");
					this.OnDiscDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscTakenAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal DiscTakenAmt
		{
			get
			{
				return this._DiscTakenAmt;
			}
			set
			{
				if ((this._DiscTakenAmt != value))
				{
					this.OnDiscTakenAmtChanging(value);
					this.SendPropertyChanging();
					this._DiscTakenAmt = value;
					this.SendPropertyChanged("DiscTakenAmt");
					this.OnDiscTakenAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOBKey", DbType="Int")]
		public System.Nullable<int> FOBKey
		{
			get
			{
				return this._FOBKey;
			}
			set
			{
				if ((this._FOBKey != value))
				{
					this.OnFOBKeyChanging(value);
					this.SendPropertyChanging();
					this._FOBKey = value;
					this.SendPropertyChanged("FOBKey");
					this.OnFOBKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal HandlAmt
		{
			get
			{
				return this._HandlAmt;
			}
			set
			{
				if ((this._HandlAmt != value))
				{
					this.OnHandlAmtChanging(value);
					this.SendPropertyChanging();
					this._HandlAmt = value;
					this.SendPropertyChanged("HandlAmt");
					this.OnHandlAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportLogKey", DbType="Int")]
		public System.Nullable<int> ImportLogKey
		{
			get
			{
				return this._ImportLogKey;
			}
			set
			{
				if ((this._ImportLogKey != value))
				{
					this.OnImportLogKeyChanging(value);
					this.SendPropertyChanging();
					this._ImportLogKey = value;
					this.SendPropertyChanged("ImportLogKey");
					this.OnImportLogKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InDispute", DbType="SmallInt NOT NULL")]
		public short InDispute
		{
			get
			{
				return this._InDispute;
			}
			set
			{
				if ((this._InDispute != value))
				{
					this.OnInDisputeChanging(value);
					this.SendPropertyChanging();
					this._InDispute = value;
					this.SendPropertyChanged("InDispute");
					this.OnInDisputeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvcFormKey", DbType="Int")]
		public System.Nullable<int> InvcFormKey
		{
			get
			{
				return this._InvcFormKey;
			}
			set
			{
				if ((this._InvcFormKey != value))
				{
					this.OnInvcFormKeyChanging(value);
					this.SendPropertyChanging();
					this._InvcFormKey = value;
					this.SendPropertyChanged("InvcFormKey");
					this.OnInvcFormKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextApplEntryNo", DbType="Int")]
		public System.Nullable<int> NextApplEntryNo
		{
			get
			{
				return this._NextApplEntryNo;
			}
			set
			{
				if ((this._NextApplEntryNo != value))
				{
					this.OnNextApplEntryNoChanging(value);
					this.SendPropertyChanging();
					this._NextApplEntryNo = value;
					this.SendPropertyChanged("NextApplEntryNo");
					this.OnNextApplEntryNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PmtTermsKey", DbType="Int")]
		public System.Nullable<int> PmtTermsKey
		{
			get
			{
				return this._PmtTermsKey;
			}
			set
			{
				if ((this._PmtTermsKey != value))
				{
					this.OnPmtTermsKeyChanging(value);
					this.SendPropertyChanging();
					this._PmtTermsKey = value;
					this.SendPropertyChanged("PmtTermsKey");
					this.OnPmtTermsKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDate", DbType="DateTime NOT NULL")]
		public System.DateTime PostDate
		{
			get
			{
				return this._PostDate;
			}
			set
			{
				if ((this._PostDate != value))
				{
					this.OnPostDateChanging(value);
					this.SendPropertyChanging();
					this._PostDate = value;
					this.SendPropertyChanged("PostDate");
					this.OnPostDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimarySperKey", DbType="Int")]
		public System.Nullable<int> PrimarySperKey
		{
			get
			{
				return this._PrimarySperKey;
			}
			set
			{
				if ((this._PrimarySperKey != value))
				{
					this.OnPrimarySperKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimarySperKey = value;
					this.SendPropertyChanged("PrimarySperKey");
					this.OnPrimarySperKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Printed", DbType="SmallInt NOT NULL")]
		public short Printed
		{
			get
			{
				return this._Printed;
			}
			set
			{
				if ((this._Printed != value))
				{
					this.OnPrintedChanging(value);
					this.SendPropertyChanging();
					this._Printed = value;
					this.SendPropertyChanged("Printed");
					this.OnPrintedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonCodeKey", DbType="Int")]
		public System.Nullable<int> ReasonCodeKey
		{
			get
			{
				return this._ReasonCodeKey;
			}
			set
			{
				if ((this._ReasonCodeKey != value))
				{
					this.OnReasonCodeKeyChanging(value);
					this.SendPropertyChanging();
					this._ReasonCodeKey = value;
					this.SendPropertyChanged("ReasonCodeKey");
					this.OnReasonCodeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurInvoiceKey", DbType="Int")]
		public System.Nullable<int> RecurInvoiceKey
		{
			get
			{
				return this._RecurInvoiceKey;
			}
			set
			{
				if ((this._RecurInvoiceKey != value))
				{
					this.OnRecurInvoiceKeyChanging(value);
					this.SendPropertyChanging();
					this._RecurInvoiceKey = value;
					this.SendPropertyChanged("RecurInvoiceKey");
					this.OnRecurInvoiceKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetntAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal RetntAmt
		{
			get
			{
				return this._RetntAmt;
			}
			set
			{
				if ((this._RetntAmt != value))
				{
					this.OnRetntAmtChanging(value);
					this.SendPropertyChanging();
					this._RetntAmt = value;
					this.SendPropertyChanged("RetntAmt");
					this.OnRetntAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetntPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> RetntPct
		{
			get
			{
				return this._RetntPct;
			}
			set
			{
				if ((this._RetntPct != value))
				{
					this.OnRetntPctChanging(value);
					this.SendPropertyChanging();
					this._RetntPct = value;
					this.SendPropertyChanged("RetntPct");
					this.OnRetntPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal SalesAmt
		{
			get
			{
				return this._SalesAmt;
			}
			set
			{
				if ((this._SalesAmt != value))
				{
					this.OnSalesAmtChanging(value);
					this.SendPropertyChanging();
					this._SalesAmt = value;
					this.SendPropertyChanged("SalesAmt");
					this.OnSalesAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal ShipAmt
		{
			get
			{
				return this._ShipAmt;
			}
			set
			{
				if ((this._ShipAmt != value))
				{
					this.OnShipAmtChanging(value);
					this.SendPropertyChanging();
					this._ShipAmt = value;
					this.SendPropertyChanged("ShipAmt");
					this.OnShipAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipMethKey", DbType="Int")]
		public System.Nullable<int> ShipMethKey
		{
			get
			{
				return this._ShipMethKey;
			}
			set
			{
				if ((this._ShipMethKey != value))
				{
					this.OnShipMethKeyChanging(value);
					this.SendPropertyChanging();
					this._ShipMethKey = value;
					this.SendPropertyChanged("ShipMethKey");
					this.OnShipMethKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAddrKey", DbType="Int NOT NULL")]
		public int ShipToAddrKey
		{
			get
			{
				return this._ShipToAddrKey;
			}
			set
			{
				if ((this._ShipToAddrKey != value))
				{
					this.OnShipToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._ShipToAddrKey = value;
					this.SendPropertyChanged("ShipToAddrKey");
					this.OnShipToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToCustAddrKey", DbType="Int")]
		public System.Nullable<int> ShipToCustAddrKey
		{
			get
			{
				return this._ShipToCustAddrKey;
			}
			set
			{
				if ((this._ShipToCustAddrKey != value))
				{
					this.OnShipToCustAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._ShipToCustAddrKey = value;
					this.SendPropertyChanged("ShipToCustAddrKey");
					this.OnShipToCustAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipZoneKey", DbType="Int")]
		public System.Nullable<int> ShipZoneKey
		{
			get
			{
				return this._ShipZoneKey;
			}
			set
			{
				if ((this._ShipZoneKey != value))
				{
					this.OnShipZoneKeyChanging(value);
					this.SendPropertyChanging();
					this._ShipZoneKey = value;
					this.SendPropertyChanged("ShipZoneKey");
					this.OnShipZoneKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceModule", DbType="SmallInt NOT NULL")]
		public short SourceModule
		{
			get
			{
				return this._SourceModule;
			}
			set
			{
				if ((this._SourceModule != value))
				{
					this.OnSourceModuleChanging(value);
					this.SendPropertyChanging();
					this._SourceModule = value;
					this.SendPropertyChanged("SourceModule");
					this.OnSourceModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt NOT NULL")]
		public short Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STaxAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal STaxAmt
		{
			get
			{
				return this._STaxAmt;
			}
			set
			{
				if ((this._STaxAmt != value))
				{
					this.OnSTaxAmtChanging(value);
					this.SendPropertyChanging();
					this._STaxAmt = value;
					this.SendPropertyChanged("STaxAmt");
					this.OnSTaxAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STaxCalc", DbType="SmallInt NOT NULL")]
		public short STaxCalc
		{
			get
			{
				return this._STaxCalc;
			}
			set
			{
				if ((this._STaxCalc != value))
				{
					this.OnSTaxCalcChanging(value);
					this.SendPropertyChanging();
					this._STaxCalc = value;
					this.SendPropertyChanged("STaxCalc");
					this.OnSTaxCalcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STaxTranKey", DbType="Int")]
		public System.Nullable<int> STaxTranKey
		{
			get
			{
				return this._STaxTranKey;
			}
			set
			{
				if ((this._STaxTranKey != value))
				{
					this.OnSTaxTranKeyChanging(value);
					this.SendPropertyChanging();
					this._STaxTranKey = value;
					this.SendPropertyChanged("STaxTranKey");
					this.OnSTaxTranKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeDiscAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal TradeDiscAmt
		{
			get
			{
				return this._TradeDiscAmt;
			}
			set
			{
				if ((this._TradeDiscAmt != value))
				{
					this.OnTradeDiscAmtChanging(value);
					this.SendPropertyChanging();
					this._TradeDiscAmt = value;
					this.SendPropertyChanged("TradeDiscAmt");
					this.OnTradeDiscAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal TranAmt
		{
			get
			{
				return this._TranAmt;
			}
			set
			{
				if ((this._TranAmt != value))
				{
					this.OnTranAmtChanging(value);
					this.SendPropertyChanging();
					this._TranAmt = value;
					this.SendPropertyChanged("TranAmt");
					this.OnTranAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranAmtHC", DbType="Decimal(15,3) NOT NULL")]
		public decimal TranAmtHC
		{
			get
			{
				return this._TranAmtHC;
			}
			set
			{
				if ((this._TranAmtHC != value))
				{
					this.OnTranAmtHCChanging(value);
					this.SendPropertyChanging();
					this._TranAmtHC = value;
					this.SendPropertyChanged("TranAmtHC");
					this.OnTranAmtHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranCmnt", DbType="VarChar(50)")]
		public string TranCmnt
		{
			get
			{
				return this._TranCmnt;
			}
			set
			{
				if ((this._TranCmnt != value))
				{
					this.OnTranCmntChanging(value);
					this.SendPropertyChanging();
					this._TranCmnt = value;
					this.SendPropertyChanged("TranCmnt");
					this.OnTranCmntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranDate", DbType="DateTime NOT NULL")]
		public System.DateTime TranDate
		{
			get
			{
				return this._TranDate;
			}
			set
			{
				if ((this._TranDate != value))
				{
					this.OnTranDateChanging(value);
					this.SendPropertyChanging();
					this._TranDate = value;
					this.SendPropertyChanged("TranDate");
					this.OnTranDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranID", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string TranID
		{
			get
			{
				return this._TranID;
			}
			set
			{
				if ((this._TranID != value))
				{
					this.OnTranIDChanging(value);
					this.SendPropertyChanging();
					this._TranID = value;
					this.SendPropertyChanged("TranID");
					this.OnTranIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranNo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TranNo
		{
			get
			{
				return this._TranNo;
			}
			set
			{
				if ((this._TranNo != value))
				{
					this.OnTranNoChanging(value);
					this.SendPropertyChanging();
					this._TranNo = value;
					this.SendPropertyChanged("TranNo");
					this.OnTranNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranType", DbType="Int NOT NULL")]
		public int TranType
		{
			get
			{
				return this._TranType;
			}
			set
			{
				if ((this._TranType != value))
				{
					this.OnTranTypeChanging(value);
					this.SendPropertyChanging();
					this._TranType = value;
					this.SendPropertyChanged("TranType");
					this.OnTranTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateCounter", DbType="Int NOT NULL")]
		public int UpdateCounter
		{
			get
			{
				return this._UpdateCounter;
			}
			set
			{
				if ((this._UpdateCounter != value))
				{
					this.OnUpdateCounterChanging(value);
					this.SendPropertyChanging();
					this._UpdateCounter = value;
					this.SendPropertyChanged("UpdateCounter");
					this.OnUpdateCounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUserID", DbType="VarChar(30)")]
		public string UpdateUserID
		{
			get
			{
				return this._UpdateUserID;
			}
			set
			{
				if ((this._UpdateUserID != value))
				{
					this.OnUpdateUserIDChanging(value);
					this.SendPropertyChanging();
					this._UpdateUserID = value;
					this.SendPropertyChanged("UpdateUserID");
					this.OnUpdateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoucherKey", DbType="Int")]
		public System.Nullable<int> VoucherKey
		{
			get
			{
				return this._VoucherKey;
			}
			set
			{
				if ((this._VoucherKey != value))
				{
					this.OnVoucherKeyChanging(value);
					this.SendPropertyChanging();
					this._VoucherKey = value;
					this.SendPropertyChanged("VoucherKey");
					this.OnVoucherKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
