#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mas500_Development_app")]
	public partial class m500ClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttarCustomer(tarCustomer instance);
    partial void UpdatetarCustomer(tarCustomer instance);
    partial void DeletetarCustomer(tarCustomer instance);
    #endregion
		
		public m500ClassDataContext() : 
				base(global::dataLib.Properties.Settings.Default.mas500_Development_appConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public m500ClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tarCustomer> tarCustomers
		{
			get
			{
				return this.GetTable<tarCustomer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tarCustomer")]
	public partial class tarCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustKey;
		
		private string _ABANo;
		
		private short _AllowCustRefund;
		
		private short _AllowWriteOff;
		
		private short _BillingType;
		
		private short _BillToNationalAcctParent;
		
		private string _CompanyID;
		
		private short _ConsolidatedStatement;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private short _CreateType;
		
		private string _CreateUserID;
		
		private decimal _CreditLimit;
		
		private short _CreditLimitAgeCat;
		
		private short _CreditLimitUsed;
		
		private string _CRMCustID;
		
		private System.Nullable<int> _CurrExchSchdKey;
		
		private int _CustClassKey;
		
		private string _CustID;
		
		private string _CustName;
		
		private string _CustRefNo;
		
		private System.Nullable<System.DateTime> _DateEstab;
		
		private int _DfltBillToAddrKey;
		
		private System.Nullable<int> _DfltItemKey;
		
		private System.Nullable<int> _DfltSalesAcctKey;
		
		private System.Nullable<int> _DfltSalesReturnAcctKey;
		
		private int _DfltShipToAddrKey;
		
		private decimal _FinChgFlatAmt;
		
		private System.Nullable<decimal> _FinChgPct;
		
		private short _Hold;
		
		private System.Nullable<int> _ImportLogKey;
		
		private System.Nullable<int> _NationalAcctLevelKey;
		
		private short _PmtByNationalAcctParent;
		
		private int _PrimaryAddrKey;
		
		private System.Nullable<int> _PrimaryCntctKey;
		
		private short _PrintDunnMsg;
		
		private System.Nullable<decimal> _ReqCreditLimit;
		
		private short _ReqPO;
		
		private System.Nullable<decimal> _RetntPct;
		
		private System.Nullable<int> _SalesSourceKey;
		
		private short _ShipPriority;
		
		private short _Status;
		
		private string _StdIndusCodeID;
		
		private System.Nullable<int> _StmtCycleKey;
		
		private System.Nullable<int> _StmtFormKey;
		
		private System.Nullable<decimal> _TradeDiscPct;
		
		private int _UpdateCounter;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _UpdateUserID;
		
		private string _UserFld1;
		
		private string _UserFld2;
		
		private string _UserFld3;
		
		private string _UserFld4;
		
		private System.Nullable<int> _VendKey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustKeyChanging(int value);
    partial void OnCustKeyChanged();
    partial void OnABANoChanging(string value);
    partial void OnABANoChanged();
    partial void OnAllowCustRefundChanging(short value);
    partial void OnAllowCustRefundChanged();
    partial void OnAllowWriteOffChanging(short value);
    partial void OnAllowWriteOffChanged();
    partial void OnBillingTypeChanging(short value);
    partial void OnBillingTypeChanged();
    partial void OnBillToNationalAcctParentChanging(short value);
    partial void OnBillToNationalAcctParentChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnConsolidatedStatementChanging(short value);
    partial void OnConsolidatedStatementChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateTypeChanging(short value);
    partial void OnCreateTypeChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCreditLimitChanging(decimal value);
    partial void OnCreditLimitChanged();
    partial void OnCreditLimitAgeCatChanging(short value);
    partial void OnCreditLimitAgeCatChanged();
    partial void OnCreditLimitUsedChanging(short value);
    partial void OnCreditLimitUsedChanged();
    partial void OnCRMCustIDChanging(string value);
    partial void OnCRMCustIDChanged();
    partial void OnCurrExchSchdKeyChanging(System.Nullable<int> value);
    partial void OnCurrExchSchdKeyChanged();
    partial void OnCustClassKeyChanging(int value);
    partial void OnCustClassKeyChanged();
    partial void OnCustIDChanging(string value);
    partial void OnCustIDChanged();
    partial void OnCustNameChanging(string value);
    partial void OnCustNameChanged();
    partial void OnCustRefNoChanging(string value);
    partial void OnCustRefNoChanged();
    partial void OnDateEstabChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEstabChanged();
    partial void OnDfltBillToAddrKeyChanging(int value);
    partial void OnDfltBillToAddrKeyChanged();
    partial void OnDfltItemKeyChanging(System.Nullable<int> value);
    partial void OnDfltItemKeyChanged();
    partial void OnDfltSalesAcctKeyChanging(System.Nullable<int> value);
    partial void OnDfltSalesAcctKeyChanged();
    partial void OnDfltSalesReturnAcctKeyChanging(System.Nullable<int> value);
    partial void OnDfltSalesReturnAcctKeyChanged();
    partial void OnDfltShipToAddrKeyChanging(int value);
    partial void OnDfltShipToAddrKeyChanged();
    partial void OnFinChgFlatAmtChanging(decimal value);
    partial void OnFinChgFlatAmtChanged();
    partial void OnFinChgPctChanging(System.Nullable<decimal> value);
    partial void OnFinChgPctChanged();
    partial void OnHoldChanging(short value);
    partial void OnHoldChanged();
    partial void OnImportLogKeyChanging(System.Nullable<int> value);
    partial void OnImportLogKeyChanged();
    partial void OnNationalAcctLevelKeyChanging(System.Nullable<int> value);
    partial void OnNationalAcctLevelKeyChanged();
    partial void OnPmtByNationalAcctParentChanging(short value);
    partial void OnPmtByNationalAcctParentChanged();
    partial void OnPrimaryAddrKeyChanging(int value);
    partial void OnPrimaryAddrKeyChanged();
    partial void OnPrimaryCntctKeyChanging(System.Nullable<int> value);
    partial void OnPrimaryCntctKeyChanged();
    partial void OnPrintDunnMsgChanging(short value);
    partial void OnPrintDunnMsgChanged();
    partial void OnReqCreditLimitChanging(System.Nullable<decimal> value);
    partial void OnReqCreditLimitChanged();
    partial void OnReqPOChanging(short value);
    partial void OnReqPOChanged();
    partial void OnRetntPctChanging(System.Nullable<decimal> value);
    partial void OnRetntPctChanged();
    partial void OnSalesSourceKeyChanging(System.Nullable<int> value);
    partial void OnSalesSourceKeyChanged();
    partial void OnShipPriorityChanging(short value);
    partial void OnShipPriorityChanged();
    partial void OnStatusChanging(short value);
    partial void OnStatusChanged();
    partial void OnStdIndusCodeIDChanging(string value);
    partial void OnStdIndusCodeIDChanged();
    partial void OnStmtCycleKeyChanging(System.Nullable<int> value);
    partial void OnStmtCycleKeyChanged();
    partial void OnStmtFormKeyChanging(System.Nullable<int> value);
    partial void OnStmtFormKeyChanged();
    partial void OnTradeDiscPctChanging(System.Nullable<decimal> value);
    partial void OnTradeDiscPctChanged();
    partial void OnUpdateCounterChanging(int value);
    partial void OnUpdateCounterChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateUserIDChanging(string value);
    partial void OnUpdateUserIDChanged();
    partial void OnUserFld1Changing(string value);
    partial void OnUserFld1Changed();
    partial void OnUserFld2Changing(string value);
    partial void OnUserFld2Changed();
    partial void OnUserFld3Changing(string value);
    partial void OnUserFld3Changed();
    partial void OnUserFld4Changing(string value);
    partial void OnUserFld4Changed();
    partial void OnVendKeyChanging(System.Nullable<int> value);
    partial void OnVendKeyChanged();
    #endregion
		
		public tarCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustKey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustKey
		{
			get
			{
				return this._CustKey;
			}
			set
			{
				if ((this._CustKey != value))
				{
					this.OnCustKeyChanging(value);
					this.SendPropertyChanging();
					this._CustKey = value;
					this.SendPropertyChanged("CustKey");
					this.OnCustKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABANo", DbType="VarChar(10)")]
		public string ABANo
		{
			get
			{
				return this._ABANo;
			}
			set
			{
				if ((this._ABANo != value))
				{
					this.OnABANoChanging(value);
					this.SendPropertyChanging();
					this._ABANo = value;
					this.SendPropertyChanged("ABANo");
					this.OnABANoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowCustRefund", DbType="SmallInt NOT NULL")]
		public short AllowCustRefund
		{
			get
			{
				return this._AllowCustRefund;
			}
			set
			{
				if ((this._AllowCustRefund != value))
				{
					this.OnAllowCustRefundChanging(value);
					this.SendPropertyChanging();
					this._AllowCustRefund = value;
					this.SendPropertyChanged("AllowCustRefund");
					this.OnAllowCustRefundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowWriteOff", DbType="SmallInt NOT NULL")]
		public short AllowWriteOff
		{
			get
			{
				return this._AllowWriteOff;
			}
			set
			{
				if ((this._AllowWriteOff != value))
				{
					this.OnAllowWriteOffChanging(value);
					this.SendPropertyChanging();
					this._AllowWriteOff = value;
					this.SendPropertyChanged("AllowWriteOff");
					this.OnAllowWriteOffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingType", DbType="SmallInt NOT NULL")]
		public short BillingType
		{
			get
			{
				return this._BillingType;
			}
			set
			{
				if ((this._BillingType != value))
				{
					this.OnBillingTypeChanging(value);
					this.SendPropertyChanging();
					this._BillingType = value;
					this.SendPropertyChanged("BillingType");
					this.OnBillingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillToNationalAcctParent", DbType="SmallInt NOT NULL")]
		public short BillToNationalAcctParent
		{
			get
			{
				return this._BillToNationalAcctParent;
			}
			set
			{
				if ((this._BillToNationalAcctParent != value))
				{
					this.OnBillToNationalAcctParentChanging(value);
					this.SendPropertyChanging();
					this._BillToNationalAcctParent = value;
					this.SendPropertyChanged("BillToNationalAcctParent");
					this.OnBillToNationalAcctParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsolidatedStatement", DbType="SmallInt NOT NULL")]
		public short ConsolidatedStatement
		{
			get
			{
				return this._ConsolidatedStatement;
			}
			set
			{
				if ((this._ConsolidatedStatement != value))
				{
					this.OnConsolidatedStatementChanging(value);
					this.SendPropertyChanging();
					this._ConsolidatedStatement = value;
					this.SendPropertyChanged("ConsolidatedStatement");
					this.OnConsolidatedStatementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateType", DbType="SmallInt NOT NULL")]
		public short CreateType
		{
			get
			{
				return this._CreateType;
			}
			set
			{
				if ((this._CreateType != value))
				{
					this.OnCreateTypeChanging(value);
					this.SendPropertyChanging();
					this._CreateType = value;
					this.SendPropertyChanged("CreateType");
					this.OnCreateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="VarChar(30)")]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Decimal(12,0) NOT NULL")]
		public decimal CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this.OnCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._CreditLimit = value;
					this.SendPropertyChanged("CreditLimit");
					this.OnCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitAgeCat", DbType="SmallInt NOT NULL")]
		public short CreditLimitAgeCat
		{
			get
			{
				return this._CreditLimitAgeCat;
			}
			set
			{
				if ((this._CreditLimitAgeCat != value))
				{
					this.OnCreditLimitAgeCatChanging(value);
					this.SendPropertyChanging();
					this._CreditLimitAgeCat = value;
					this.SendPropertyChanged("CreditLimitAgeCat");
					this.OnCreditLimitAgeCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitUsed", DbType="SmallInt NOT NULL")]
		public short CreditLimitUsed
		{
			get
			{
				return this._CreditLimitUsed;
			}
			set
			{
				if ((this._CreditLimitUsed != value))
				{
					this.OnCreditLimitUsedChanging(value);
					this.SendPropertyChanging();
					this._CreditLimitUsed = value;
					this.SendPropertyChanged("CreditLimitUsed");
					this.OnCreditLimitUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRMCustID", DbType="VarChar(32)")]
		public string CRMCustID
		{
			get
			{
				return this._CRMCustID;
			}
			set
			{
				if ((this._CRMCustID != value))
				{
					this.OnCRMCustIDChanging(value);
					this.SendPropertyChanging();
					this._CRMCustID = value;
					this.SendPropertyChanged("CRMCustID");
					this.OnCRMCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrExchSchdKey", DbType="Int")]
		public System.Nullable<int> CurrExchSchdKey
		{
			get
			{
				return this._CurrExchSchdKey;
			}
			set
			{
				if ((this._CurrExchSchdKey != value))
				{
					this.OnCurrExchSchdKeyChanging(value);
					this.SendPropertyChanging();
					this._CurrExchSchdKey = value;
					this.SendPropertyChanged("CurrExchSchdKey");
					this.OnCurrExchSchdKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustClassKey", DbType="Int NOT NULL")]
		public int CustClassKey
		{
			get
			{
				return this._CustClassKey;
			}
			set
			{
				if ((this._CustClassKey != value))
				{
					this.OnCustClassKeyChanging(value);
					this.SendPropertyChanging();
					this._CustClassKey = value;
					this.SendPropertyChanged("CustClassKey");
					this.OnCustClassKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CustID
		{
			get
			{
				return this._CustID;
			}
			set
			{
				if ((this._CustID != value))
				{
					this.OnCustIDChanging(value);
					this.SendPropertyChanging();
					this._CustID = value;
					this.SendPropertyChanged("CustID");
					this.OnCustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string CustName
		{
			get
			{
				return this._CustName;
			}
			set
			{
				if ((this._CustName != value))
				{
					this.OnCustNameChanging(value);
					this.SendPropertyChanging();
					this._CustName = value;
					this.SendPropertyChanged("CustName");
					this.OnCustNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustRefNo", DbType="VarChar(15)")]
		public string CustRefNo
		{
			get
			{
				return this._CustRefNo;
			}
			set
			{
				if ((this._CustRefNo != value))
				{
					this.OnCustRefNoChanging(value);
					this.SendPropertyChanging();
					this._CustRefNo = value;
					this.SendPropertyChanged("CustRefNo");
					this.OnCustRefNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEstab", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEstab
		{
			get
			{
				return this._DateEstab;
			}
			set
			{
				if ((this._DateEstab != value))
				{
					this.OnDateEstabChanging(value);
					this.SendPropertyChanging();
					this._DateEstab = value;
					this.SendPropertyChanged("DateEstab");
					this.OnDateEstabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltBillToAddrKey", DbType="Int NOT NULL")]
		public int DfltBillToAddrKey
		{
			get
			{
				return this._DfltBillToAddrKey;
			}
			set
			{
				if ((this._DfltBillToAddrKey != value))
				{
					this.OnDfltBillToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltBillToAddrKey = value;
					this.SendPropertyChanged("DfltBillToAddrKey");
					this.OnDfltBillToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltItemKey", DbType="Int")]
		public System.Nullable<int> DfltItemKey
		{
			get
			{
				return this._DfltItemKey;
			}
			set
			{
				if ((this._DfltItemKey != value))
				{
					this.OnDfltItemKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltItemKey = value;
					this.SendPropertyChanged("DfltItemKey");
					this.OnDfltItemKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltSalesAcctKey", DbType="Int")]
		public System.Nullable<int> DfltSalesAcctKey
		{
			get
			{
				return this._DfltSalesAcctKey;
			}
			set
			{
				if ((this._DfltSalesAcctKey != value))
				{
					this.OnDfltSalesAcctKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltSalesAcctKey = value;
					this.SendPropertyChanged("DfltSalesAcctKey");
					this.OnDfltSalesAcctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltSalesReturnAcctKey", DbType="Int")]
		public System.Nullable<int> DfltSalesReturnAcctKey
		{
			get
			{
				return this._DfltSalesReturnAcctKey;
			}
			set
			{
				if ((this._DfltSalesReturnAcctKey != value))
				{
					this.OnDfltSalesReturnAcctKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltSalesReturnAcctKey = value;
					this.SendPropertyChanged("DfltSalesReturnAcctKey");
					this.OnDfltSalesReturnAcctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DfltShipToAddrKey", DbType="Int NOT NULL")]
		public int DfltShipToAddrKey
		{
			get
			{
				return this._DfltShipToAddrKey;
			}
			set
			{
				if ((this._DfltShipToAddrKey != value))
				{
					this.OnDfltShipToAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._DfltShipToAddrKey = value;
					this.SendPropertyChanged("DfltShipToAddrKey");
					this.OnDfltShipToAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChgFlatAmt", DbType="Decimal(15,3) NOT NULL")]
		public decimal FinChgFlatAmt
		{
			get
			{
				return this._FinChgFlatAmt;
			}
			set
			{
				if ((this._FinChgFlatAmt != value))
				{
					this.OnFinChgFlatAmtChanging(value);
					this.SendPropertyChanging();
					this._FinChgFlatAmt = value;
					this.SendPropertyChanged("FinChgFlatAmt");
					this.OnFinChgFlatAmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChgPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> FinChgPct
		{
			get
			{
				return this._FinChgPct;
			}
			set
			{
				if ((this._FinChgPct != value))
				{
					this.OnFinChgPctChanging(value);
					this.SendPropertyChanging();
					this._FinChgPct = value;
					this.SendPropertyChanged("FinChgPct");
					this.OnFinChgPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hold", DbType="SmallInt NOT NULL")]
		public short Hold
		{
			get
			{
				return this._Hold;
			}
			set
			{
				if ((this._Hold != value))
				{
					this.OnHoldChanging(value);
					this.SendPropertyChanging();
					this._Hold = value;
					this.SendPropertyChanged("Hold");
					this.OnHoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportLogKey", DbType="Int")]
		public System.Nullable<int> ImportLogKey
		{
			get
			{
				return this._ImportLogKey;
			}
			set
			{
				if ((this._ImportLogKey != value))
				{
					this.OnImportLogKeyChanging(value);
					this.SendPropertyChanging();
					this._ImportLogKey = value;
					this.SendPropertyChanged("ImportLogKey");
					this.OnImportLogKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalAcctLevelKey", DbType="Int")]
		public System.Nullable<int> NationalAcctLevelKey
		{
			get
			{
				return this._NationalAcctLevelKey;
			}
			set
			{
				if ((this._NationalAcctLevelKey != value))
				{
					this.OnNationalAcctLevelKeyChanging(value);
					this.SendPropertyChanging();
					this._NationalAcctLevelKey = value;
					this.SendPropertyChanged("NationalAcctLevelKey");
					this.OnNationalAcctLevelKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PmtByNationalAcctParent", DbType="SmallInt NOT NULL")]
		public short PmtByNationalAcctParent
		{
			get
			{
				return this._PmtByNationalAcctParent;
			}
			set
			{
				if ((this._PmtByNationalAcctParent != value))
				{
					this.OnPmtByNationalAcctParentChanging(value);
					this.SendPropertyChanging();
					this._PmtByNationalAcctParent = value;
					this.SendPropertyChanged("PmtByNationalAcctParent");
					this.OnPmtByNationalAcctParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddrKey", DbType="Int NOT NULL")]
		public int PrimaryAddrKey
		{
			get
			{
				return this._PrimaryAddrKey;
			}
			set
			{
				if ((this._PrimaryAddrKey != value))
				{
					this.OnPrimaryAddrKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimaryAddrKey = value;
					this.SendPropertyChanged("PrimaryAddrKey");
					this.OnPrimaryAddrKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCntctKey", DbType="Int")]
		public System.Nullable<int> PrimaryCntctKey
		{
			get
			{
				return this._PrimaryCntctKey;
			}
			set
			{
				if ((this._PrimaryCntctKey != value))
				{
					this.OnPrimaryCntctKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCntctKey = value;
					this.SendPropertyChanged("PrimaryCntctKey");
					this.OnPrimaryCntctKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintDunnMsg", DbType="SmallInt NOT NULL")]
		public short PrintDunnMsg
		{
			get
			{
				return this._PrintDunnMsg;
			}
			set
			{
				if ((this._PrintDunnMsg != value))
				{
					this.OnPrintDunnMsgChanging(value);
					this.SendPropertyChanging();
					this._PrintDunnMsg = value;
					this.SendPropertyChanged("PrintDunnMsg");
					this.OnPrintDunnMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqCreditLimit", DbType="Decimal(15,3)")]
		public System.Nullable<decimal> ReqCreditLimit
		{
			get
			{
				return this._ReqCreditLimit;
			}
			set
			{
				if ((this._ReqCreditLimit != value))
				{
					this.OnReqCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._ReqCreditLimit = value;
					this.SendPropertyChanged("ReqCreditLimit");
					this.OnReqCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqPO", DbType="SmallInt NOT NULL")]
		public short ReqPO
		{
			get
			{
				return this._ReqPO;
			}
			set
			{
				if ((this._ReqPO != value))
				{
					this.OnReqPOChanging(value);
					this.SendPropertyChanging();
					this._ReqPO = value;
					this.SendPropertyChanged("ReqPO");
					this.OnReqPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetntPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> RetntPct
		{
			get
			{
				return this._RetntPct;
			}
			set
			{
				if ((this._RetntPct != value))
				{
					this.OnRetntPctChanging(value);
					this.SendPropertyChanging();
					this._RetntPct = value;
					this.SendPropertyChanged("RetntPct");
					this.OnRetntPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesSourceKey", DbType="Int")]
		public System.Nullable<int> SalesSourceKey
		{
			get
			{
				return this._SalesSourceKey;
			}
			set
			{
				if ((this._SalesSourceKey != value))
				{
					this.OnSalesSourceKeyChanging(value);
					this.SendPropertyChanging();
					this._SalesSourceKey = value;
					this.SendPropertyChanged("SalesSourceKey");
					this.OnSalesSourceKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPriority", DbType="SmallInt NOT NULL")]
		public short ShipPriority
		{
			get
			{
				return this._ShipPriority;
			}
			set
			{
				if ((this._ShipPriority != value))
				{
					this.OnShipPriorityChanging(value);
					this.SendPropertyChanging();
					this._ShipPriority = value;
					this.SendPropertyChanged("ShipPriority");
					this.OnShipPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt NOT NULL")]
		public short Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdIndusCodeID", DbType="VarChar(7)")]
		public string StdIndusCodeID
		{
			get
			{
				return this._StdIndusCodeID;
			}
			set
			{
				if ((this._StdIndusCodeID != value))
				{
					this.OnStdIndusCodeIDChanging(value);
					this.SendPropertyChanging();
					this._StdIndusCodeID = value;
					this.SendPropertyChanged("StdIndusCodeID");
					this.OnStdIndusCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtCycleKey", DbType="Int")]
		public System.Nullable<int> StmtCycleKey
		{
			get
			{
				return this._StmtCycleKey;
			}
			set
			{
				if ((this._StmtCycleKey != value))
				{
					this.OnStmtCycleKeyChanging(value);
					this.SendPropertyChanging();
					this._StmtCycleKey = value;
					this.SendPropertyChanged("StmtCycleKey");
					this.OnStmtCycleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtFormKey", DbType="Int")]
		public System.Nullable<int> StmtFormKey
		{
			get
			{
				return this._StmtFormKey;
			}
			set
			{
				if ((this._StmtFormKey != value))
				{
					this.OnStmtFormKeyChanging(value);
					this.SendPropertyChanging();
					this._StmtFormKey = value;
					this.SendPropertyChanged("StmtFormKey");
					this.OnStmtFormKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeDiscPct", DbType="Decimal(5,4)")]
		public System.Nullable<decimal> TradeDiscPct
		{
			get
			{
				return this._TradeDiscPct;
			}
			set
			{
				if ((this._TradeDiscPct != value))
				{
					this.OnTradeDiscPctChanging(value);
					this.SendPropertyChanging();
					this._TradeDiscPct = value;
					this.SendPropertyChanged("TradeDiscPct");
					this.OnTradeDiscPctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateCounter", DbType="Int NOT NULL")]
		public int UpdateCounter
		{
			get
			{
				return this._UpdateCounter;
			}
			set
			{
				if ((this._UpdateCounter != value))
				{
					this.OnUpdateCounterChanging(value);
					this.SendPropertyChanging();
					this._UpdateCounter = value;
					this.SendPropertyChanged("UpdateCounter");
					this.OnUpdateCounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateUserID", DbType="VarChar(30)")]
		public string UpdateUserID
		{
			get
			{
				return this._UpdateUserID;
			}
			set
			{
				if ((this._UpdateUserID != value))
				{
					this.OnUpdateUserIDChanging(value);
					this.SendPropertyChanging();
					this._UpdateUserID = value;
					this.SendPropertyChanged("UpdateUserID");
					this.OnUpdateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld1", DbType="VarChar(15)")]
		public string UserFld1
		{
			get
			{
				return this._UserFld1;
			}
			set
			{
				if ((this._UserFld1 != value))
				{
					this.OnUserFld1Changing(value);
					this.SendPropertyChanging();
					this._UserFld1 = value;
					this.SendPropertyChanged("UserFld1");
					this.OnUserFld1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld2", DbType="VarChar(15)")]
		public string UserFld2
		{
			get
			{
				return this._UserFld2;
			}
			set
			{
				if ((this._UserFld2 != value))
				{
					this.OnUserFld2Changing(value);
					this.SendPropertyChanging();
					this._UserFld2 = value;
					this.SendPropertyChanged("UserFld2");
					this.OnUserFld2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld3", DbType="VarChar(15)")]
		public string UserFld3
		{
			get
			{
				return this._UserFld3;
			}
			set
			{
				if ((this._UserFld3 != value))
				{
					this.OnUserFld3Changing(value);
					this.SendPropertyChanging();
					this._UserFld3 = value;
					this.SendPropertyChanged("UserFld3");
					this.OnUserFld3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFld4", DbType="VarChar(15)")]
		public string UserFld4
		{
			get
			{
				return this._UserFld4;
			}
			set
			{
				if ((this._UserFld4 != value))
				{
					this.OnUserFld4Changing(value);
					this.SendPropertyChanging();
					this._UserFld4 = value;
					this.SendPropertyChanged("UserFld4");
					this.OnUserFld4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendKey", DbType="Int")]
		public System.Nullable<int> VendKey
		{
			get
			{
				return this._VendKey;
			}
			set
			{
				if ((this._VendKey != value))
				{
					this.OnVendKeyChanging(value);
					this.SendPropertyChanging();
					this._VendKey = value;
					this.SendPropertyChanged("VendKey");
					this.OnVendKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
